name: Benchmarking Tests at Scale
on:
  pull_request:
    branches:
      - "main"
      - "release/v*"
  workflow_dispatch:
    inputs:
      rps:
        description: "The target requests-per-second rate. Default: 1000"
        default: '1000'
        type: string
        required: false
      connections:
        description: "The maximum allowed number of concurrent connections per event loop. HTTP/1 only. Default: 100."
        default: '100'
        type: string
        required: false
      duration:
        description: "The number of seconds that the test should run. Default: 90."
        default: '90'
        type: string
        required: false

jobs:
  benchmark-test:
    name: Benchmark Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./tools/github-actions/setup-deps

      - name: Run Benchmark tests
        env:
          KIND_NODE_TAG: v1.28.0
          IMAGE_PULL_POLICY: IfNotPresent
          RPS: ${{ github.event.inputs.rps || 1000 }}
          CONNECTIONS: ${{ github.event.inputs.connections || 100 }}
          DURATION: ${{ github.event.inputs.duration || 90 }}
        run: make benchmark
